### ISSUE TITLE
Visual Enhancements

### ISSUE THREAD

**Issue by ricardobaeta** [gitterHQ/hitchhikers#11]
@cutandpastey 

**Homepage**
- [x] All sub-headings color: #5d98af;
- [x] Github icon should be vertical-aligned with the CTA copy

**Form**
- [x] All sub-headings color: #5d98af;
- [x] Could you make the entire email block the same width as the location? (the toggle stays the same)

**People you should meet**
- [x] All sub-headings color: #5d98af;
- [x] "WE TOOK A LOOK OF SOME OF YOUR PUBLIC DATA ON GITHUB AND TRIED TO FIND FOLLOWERS, FELLOW CONTRIBUTERS AND OTHER PEOPLE WE THING YOU SHOULD MEET." line-height: 24px; (i think we can do this for all sub-heading because in responsive they will break lines)
- [x] The sub-heading mentioned above should have margin-bottom: 72px;
- [x] Suggestion reason should have line-height: 18px; 
- [x] leaderboard__items__item element should have min-width: 226px;
- [x] leaderboard__items__item element should have margin-bottom: 1rem;

I think that's it for now. Let's see how it goes :)
