### ISSUE TITLE
List o' Issues

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/hitchhikers#9]
### Front Page
- [x] Need to remove Sidecar until Gitter webapp that supports sidecar ships
- [ ] Sidecar position is wrong
- [ ] Is the top area too dominant/high?
- [ ] More obvious value proposition
- [ ] Contrast
- [ ] A map
- [x] Leaderboards not showing anything
### Login
- [x] Need to use a different app, not Le Roux's personal account
- [x] Can't go back
### Form
- [ ] Do we really need the provence?
- [x] Can we remove powered by Google?
- [x] The width of the location input field isn't wide enough / text is too large
- [x] Remove No Yes button next to country
- [ ] Find me button to autopopulate 
- [x] Remove public attendance option
- [x] Email is not populating
### Mobile
- [ ] Doesn't seem to work at all
### TODO
- [ ] Emailer thingy to email people
- [x] Domain
